# Generated by Django 4.0 on 2022-01-26 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_author_person_reaction_comment_new_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.person'),
        ),
    ]
